 // Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        agp_version = '9.4.0'
    }
    repositories {
        maven { url 'https://maven.google.com/' }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath 'com.google.gms:google-services:4.5.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.8'

    }
}

allprojects {
    repositories {
        maven {
            url "https://jitpack.io"
        }
        maven {
            url "https://artifactory.paytm.in/libs-release-local"
        }
        maven {
            url 'https://maven.cashfree.com/release'
        }
        google()
        mavenCentral()
        flatDir {
            dirs 'libs'
        }
        google()
    }

}
 tasks.register('clean', Delete) {
     delete rootProject.buildDir
 }

