apply plugin: 'com.android.library'

repositories {
    mavenCentral()
}

android {
    compileSdkVersion 37
    defaultConfig {
        minSdkVersion 24
    }
    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            jniLibs.srcDirs = ['libs']
        }
    }
    namespace "com.special.ResideMenu"
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.nineoldandroids:library:2.4.0'
}

